### ISSUE TITLE
cannot run as a package

### ISSUE THREAD

**Issue by namespacestd0** [biothings/biothings_schema.py#19]
I have observed two potential issues here:

First, the pip command here seems to contain a typo:
On https://github.com/biothings/biothings_schema.py/blame/master/README.md#L108, it shows 
$ pip install git+https://github.com/biothings/biothings_schema.py#egg=biothings_schema.py,
did you mean
$ pip install git+https://github.com/biothings/biothings_schema.py#egg=biothings_schema?

Second, commit versions like 0b3a9e1 cannot run as a package, steps to reproduce:
```
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from biothings_schema import Schema
>>> se = Schema()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jerry\Envs\testkevinparser\lib\site-packages\biothings_schema\__init__.py", line 167, in __init__
    self.load_default_schema()
  File "C:\Users\Jerry\Envs\testkevinparser\lib\site-packages\biothings_schema\__init__.py", line 243, in load_default_schema
    self.extended_class_only_graph = self.schema_extension_nx.subgraph([node for node, attrdict in self.schema_extension_nx.node.items() if attrdict['type'] == 'Class' and node not in isolates])
AttributeError: 'DiGraph' object has no attribute 'node'
>>> import biothings_schema
>>> biothings_schema.__path__
['C:\\Users\\Jerry\\Envs\\testkevinparser\\lib\\site-packages\\biothings_schema']
```

Directly running the file from the folder in certain environment seems to be fine:
```
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:05:16) [MSC v.1915 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from biothings_schema import Schema
>>> import biothings_schema
>>> biothings_schema.__path__
['C:\\Users\\Jerry\\Code\\biothings_schema.py\\biothings_schema']
>>> Schema()
<biothings_schema.Schema object at 0x0170AF70>
```

Let me know if there's anything I need to do differently. 
It could be that non-enforced newer dependency versions are available that bring a compatibility problem. Just a random guess.

**Comment by kevinxin90** [comment]
1. First is correct, I have fixed the README file.
2. Second is because of the recent update of a package which this one depends on. Now I have updated the setup.py file so that we don't use the latest version of the package.
@namespacestd0 Feel free to try again.

**Comment by namespacestd0** [comment]
Awesome, thanks so much!
