### ISSUE TITLE
Web visualization templates

### ISSUE THREAD

**Issue by milen-sage** [biothings/biothings_schema.py#5]
I have a sample containing about half of our metadata already schematized into a (work-in-progress) data model using the SE. I was wondering @kevinxin90 could you or someone else point me to a code/tool for processing the schema into web visualization templates (e.g. linked data graph and dictionary pages)? I remember someone from Scripps presented along these lines at one of the earlier data discovery WG meeting.

graphviz works fine, but I want to showcase at our internal Sage metadata WG how we can plugin into existing already styled web templates (if available). If this is not available, we can collaborate on that as well.

**Comment by milen-sage** [comment]
Actually, I tested http://discovery.biothings.io

It ingested our json-ld very nicely! The little js graph widget is slick :)

Is there a repository for the web interface of http://discovery.biothings.io we can check out?

**Comment by kevinxin90** [comment]
@milen-sage Yes. Here is the repo: https://github.com/biothings/discovery-app
